---
name: Update Skeleton JSON

on:
  push:
    branches:
      - testing/commit_on_merge_base

env:
  WORKING_BRANCH_NAME: update_json_file

jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CISAGOVBOT_PAT }}
      - id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Update Python base packages
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: pip install --upgrade --requirement scripts/requirements.txt
      - name: Generate a JSON from the manually maintained YAML file
        run: python3 scripts/generate_json.py data/content.yml data/content.json
      - name: Configure git
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@github.com
      - name: Create the branch for test validation
        run: git switch --create ${{ env.WORKING_BRANCH_NAME }}
      - id: commit-json-for-testing
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ env.WORKING_BRANCH_NAME }}
          commit_message: Generate an updated JSON file
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor }}@github.com
          file_pattern: data/content.json
      - uses: lewagon/wait-on-check-action@v1.0.0
        if: steps.commit-json-for-testing.outputs.changes_detected
        with:
          check-name: lint
          ref: ${{ env.WORKING_BRANCH_NAME }}
          repo-token: ${{ github.token }}
      - name: Merge the testing branch
        if: steps.commit-json-for-testing.outputs.changes_detected
        run: |
          git switch ${{ github.ref_name }}
          git merge ${{ env.WORKING_BRANCH_NAME }}
          git push
          git push -d origin ${{ env.WORKING_BRANCH_NAME }}
